### ISSUE TITLE
Add manual trigger

### ISSUE THREAD

**Issue by daveroberts** [Raynos/live-reload#12]
I want to reload the page by issuing a command, not when files change.  Is this possible?

The reason is that my files will change but are then transformed (changed again).  I only want to reload the browser once, on the second change.

**Comment by Yaakov-Belch** [comment]
You can do this already now:
* execute the command `touch ping-file` whenever you want to reload.
* let live-reload just watch that one `ping-file`.

**Comment by Yaakov-Belch** [comment]
You can do this now:
- In your build script, execute the command `touch reload-file` when your files have changed.
- let live-reload watch just the one `reload-file`.

**Comment by daveroberts** [comment]
Thanks, I think that's a working solution.  So simple, I should have seen it originally
