### ISSUE TITLE
No Reload when whole directory is replaced

### ISSUE THREAD

**Issue by woodyrew** [Raynos/live-reload#9]
I have a build script the removes the served directory and replaces it with the new content.
e.g.
`./dest` is removed, the new content is placed in `./dest`.

I'm watching `./dest` with the following command:

```
$ live-reload --port=9091 --delay=500 ./dest
```

This action does not trigger a browser refresh. Is there a way to send a message to live-reload or a way around this?

**Comment by Yaakov-Belch** [comment]
You can do this now:
- In your build script, execute the command `touch reload-file` when your files have changed.
- let live-reload watch just the one `reload-file`.

**Comment by woodyrew** [comment]
Good to know, thanks. I worked around by calling `browser-sync reload` after my build.
